### ISSUE TITLE
Why not create our OWN HOSTED WEBSITE WITH REPOS AND APPS?

### ISSUE THREAD

**Issue by peggy-48** [Rikj000/XWaydroid#1]
Yeah, for FOSS privacy lovers like me and you, androidacy is crap, so why not create a free no-cost website and repos (i have a completely free hosting service btw), that would help the FOSS users of Android to not struggle to that big giant repo eater..

**Comment by Rikj000** [comment]
Hi @peggy-48 :wave: 

I believe [MRepo](https://github.com/MRepoApp/MRepo) will be the way forward.   
Which is an open source, privacy respecting, federated/de-centralized way of dealing with multiple Magisk Repos.

Recently I setup my own [Magisk-Modules-Rikj000-Repo](https://github.com/Rikj000/Magisk-Modules-Rikj000-Repo),   
which you can import in your MRepo app to get access to the official downloads of my modules.

See the [Magisk-Manager-for-Recovery-Mode - Docs - MRepo](https://github.com/Rikj000/Magisk-Manager-for-Recovery-Mode#mrepo) for setup instructions.

I will be closing this issue because it's off-topic *([XWaydroid](https://github.com/Rikj000/XWaydroid/) is Linux software, unrelated to Magisk Modules)*.   
However feel free to continue the conversation if you have more questions :slightly_smiling_face:

**Comment by peggy-48** [comment]
Really that is kinda a good idea to look forward by using MRepo because it's less aggressive.
